version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  allow:
    - dependency-name: "clean-css"
    - dependency-name: "esbuild"
    - dependency-name: "fontfaceobserver"
    - dependency-name: "hashids"
    - dependency-name: "lodash-es"
    - dependency-name: "utility-types"
    - dependency-name: "zod"
    - dependency-name: "*"
      dependency-type: "production"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
  open-pull-requests-limit: 10
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    include: scope
