version: 2
updates:
- package-ecosystem: npm
  directory: "/example"
  allow:
    - dependency-name: "*"
      dependency-type: "production"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
  open-pull-requests-limit: 10
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: npm
  directory: "/"
  allow:
    - dependency-name: "@types/bytes"
    - dependency-name: "@types/clean-css"
    - dependency-name: "@types/fontfaceobserver"
    - dependency-name: "@types/lodash-es"
    - dependency-name: "@types/url-join"
    - dependency-name: "@types/wrap-ansi"
    - dependency-name: "arg"
    - dependency-name: "brotli-size"
    - dependency-name: "bytes"
    - dependency-name: "chalk"
    - dependency-name: "clean-css"
    - dependency-name: "esbuild"
    - dependency-name: "execa"
    - dependency-name: "find-up"
    - dependency-name: "fontfaceobserver"
    - dependency-name: "fs-extra"
    - dependency-name: "gzip-size"
    - dependency-name: "hashids"
    - dependency-name: "lodash-es"
    - dependency-name: "ora"
    - dependency-name: "url-join"
    - dependency-name: "utility-types"
    - dependency-name: "wrap-ansi"
    - dependency-name: "zod"
    - dependency-name: "*"
      dependency-type: "production"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
  open-pull-requests-limit: 10
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: GMT
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    include: scope
