#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
set -euo pipefail

npx syncpack fix-mismatches --source 'package.json' --source 'example/package.json' || exit 1
npx syncpack set-semver-ranges --dev --source 'package.json' --source 'example/package.json' || exit 1
npx syncpack format --source 'package.json' --source 'example/package.json' || exit 1

npm run lint || exit 1
npx --no-install lint-staged || exit 1
npm run typecheck && cd example && npm run typecheck && cd ../ || exit 1
npm run test || exit 1
