#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm exec syncpack fix-mismatches --source 'package.json' --source 'example/package.json' || exit 1
pnpm exec syncpack set-semver-ranges --dev --source 'package.json' --source 'example/package.json' || exit 1
pnpm exec syncpack format --source 'package.json' --source 'example/package.json' || exit 1

pnpm install --lockfile-only
git add package.json example/package.json pnpm-lock.yaml

pnpm run lint || exit 1
pnpm exec lint-staged || exit 1
pnpm run typecheck && cd example && npm run typecheck && cd ../ || exit 1
pnpm run test || exit 1
